# Generated by Django 4.1.7 on 2023-04-01 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offer", "0003_candidates"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candidates",
            new_name="Candidate",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="last_date",
            new_name="expiration_date",
        ),
    ]
