# Generated by Django 4.1.7 on 2023-03-31 15:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import offer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, null=True)),
                ("description", models.TextField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address", models.CharField(max_length=70, null=True)),
                (
                    "jobType",
                    models.CharField(
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Temporary", "Temporary"),
                            ("Internship", "Internship"),
                        ],
                        default="Internship",
                        max_length=10,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("Finance", "Finance"),
                            ("Information Technology", "It"),
                            ("Banking", "Banking"),
                            ("Education", "Education"),
                            ("Telecommunication", "Telecommunication"),
                        ],
                        default="Finance",
                        max_length=30,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("No Experience", "No Experience"),
                            ("1 Years", "One Year"),
                            ("2 Years", "Two Year"),
                        ],
                        default="No Experience",
                        max_length=22,
                    ),
                ),
                (
                    "month_salary",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(500),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                    ),
                ),
                ("positions", models.IntegerField(default=1)),
                ("company", models.CharField(max_length=50, null=True)),
                (
                    "last_date",
                    models.DateTimeField(
                        default=offer.models.return_expiration_date_time
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
