# Generated by Django 4.1.7 on 2023-03-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="jobType",
            new_name="job_type",
        ),
    ]
